version: '2'
services:
    twitteralert-app:
        image: twitteralert
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://twitteralert-postgresql:5432/twitteralert
            - JHIPSTER_SLEEP=10
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=zookeeper
        ports:
            - 8080:8080
    twitteralert-postgresql:
        image: postgres:10.4
        environment:
            - POSTGRES_USER=twitteralert
            - POSTGRES_PASSWORD=
    
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper
    kafka:
        extends:
            file: kafka.yml
            service: kafka
